





pipeline:

  env:
    image: node:12-alpine
    commands:
      - export

  release:
    image: node:12-alpine
    commands:
      - export HOME=$${DRONE_WORKSPACE}
      - apk --no-cache add git libc6-compat
      - wget -O - https://github.com/cli/cli/releases/download/v1.2.0/gh_1.2.0_linux_amd64.tar.gz | tar xzvf -
      - chmod +x gh_1.2.0_linux_amd64/bin/gh 
      - npx github-release-notes@0.17.1 release --token=$GITHUB_TOKEN
      - npx github-release-notes@0.17.1 changelog --override --token=$GITHUB_TOKEN
      - git config user.name $DRONE_COMMIT_AUTHOR
      - git config user.email $DRONE_COMMIT_AUTHOR_EMAIL
      - git checkout -B changelog-$DRONE_TAG
      - git add CHANGELOG.md
      - git commit -m "add changelog for $DRONE_TAG"
      - git push -u https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$DRONE_REPO_OWNER/$DRONE_REPO_NAME.git changelog-$DRONE_TAG > /dev/null 2>&1
      - GITHUB_TOKEN=$GITHUB_TOKEN ./gh_1.2.0_linux_amd64/bin/gh pr create --base master --head changelog-$DRONE_TAG --reviewer $DRONE_COMMIT_AUTHOR --title " add changelog for $DRONE_TAG" --body ""
    secrets: [ github_token, github_user ]
    when:
      event: [tag]


